server:
  port : 8888
spring:
  application:
    name : config-server
  cloud:
    config:
      label : master
      server :
        git:
          uri : https://github.com/RevelationCollection/simple
          searchPaths : config-server/src/main/resources/
          username :
          password :