server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 集群 ,127.0.0.1:8760/eureka,127.0.0.1:8759/eureka

spring:
  application:
    name: eurka-server

